sudo: required

services:
  - docker

before_install:
  - docker build -t brytebee/docker-react -f Dockerfile.dev .

scripts:
  # - docker run --rm timeout 10 brytebee/docker-react sh -c "npm run test -- --coverage && exit $?"
  - docker run -e CI=true brytebee/docker-react npm run test
