sudo: required

services:
  - docker

before_install:
  - docker build -t brytebee/docker-react -f Dockerfile.dev .

scripts:
  - docker run --rm brytebee/docker-react sh -c "npm run test -- --coverage && exit $?"
